/*
 * generated by Xtext 2.24.0
 */
package mdd.coursework.xcss.ui.tests;

import com.google.inject.Injector;
import mdd.coursework.xcss.ui.internal.XcssActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class XcssUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XcssActivator.getInstance().getInjector("mdd.coursework.xcss.Xcss");
	}

}
