/*
 * generated by Xtext 2.24.0
 */
package mdd.coursework.xcss.parser.antlr;

import mdd.coursework.xcss.parser.antlr.internal.InternalXcssParser;
import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;

public class XcssTokenSource extends AbstractIndentationTokenSource {

	public XcssTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalXcssParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalXcssParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalXcssParser.RULE_END;
	}

}
