/*
 * generated by Xtext 2.24.0
 */
package mdd.coursework.xcss.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractXcssScopeProvider extends DelegatingScopeProvider {
}
