/*
 * generated by Xtext 2.24.0
 */
package mdd.coursework.xcss;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class XcssStandaloneSetup extends XcssStandaloneSetupGenerated {

	public static void doSetup() {
		new XcssStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
