/*
 * generated by Xtext 2.24.0
 */
package mdd.coursework.xcss.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import mdd.coursework.xcss.XcssRuntimeModule;
import mdd.coursework.xcss.XcssStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class XcssIdeSetup extends XcssStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new XcssRuntimeModule(), new XcssIdeModule()));
	}
	
}
