/*
 * generated by Xtext 2.24.0
 */
package mdd.coursework.xcss.parser.antlr;

import com.google.inject.Inject;
import mdd.coursework.xcss.parser.antlr.internal.InternalXcssParser;
import mdd.coursework.xcss.services.XcssGrammarAccess;
import org.antlr.runtime.CharStream;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class XcssParser extends AbstractAntlrParser {

	@Inject
	private XcssGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected TokenSource createLexer(CharStream stream) {
		return new XcssTokenSource(super.createLexer(stream));
	}
	
	/**
	 * Indentation aware languages do not support partial parsing since the lexer is inherently stateful.
	 * Override and return {@code true} if your terminal splitting is stateless.
	 */
	@Override
	protected boolean isReparseSupported() {
		return false;
	}

	@Override
	protected InternalXcssParser createParser(XtextTokenStream stream) {
		return new InternalXcssParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "XcssModel";
	}

	public XcssGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(XcssGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
