/*
 * generated by Xtext 2.24.0
 */
package mdd.coursework.xcss.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class XcssAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("mdd/coursework/xcss/parser/antlr/internal/InternalXcssParser.tokens");
	}
}
