/**
 * generated by Xtext 2.24.0
 */
package mdd.coursework.xcss.xcss;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CSS Style Delacration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdd.coursework.xcss.xcss.CSSStyleDelacration#getCssStyleKey <em>Css Style Key</em>}</li>
 *   <li>{@link mdd.coursework.xcss.xcss.CSSStyleDelacration#getCssStyleValue <em>Css Style Value</em>}</li>
 * </ul>
 *
 * @see mdd.coursework.xcss.xcss.XcssPackage#getCSSStyleDelacration()
 * @model
 * @generated
 */
public interface CSSStyleDelacration extends EObject
{
  /**
   * Returns the value of the '<em><b>Css Style Key</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Css Style Key</em>' containment reference.
   * @see #setCssStyleKey(CSSStyleKey)
   * @see mdd.coursework.xcss.xcss.XcssPackage#getCSSStyleDelacration_CssStyleKey()
   * @model containment="true"
   * @generated
   */
  CSSStyleKey getCssStyleKey();

  /**
   * Sets the value of the '{@link mdd.coursework.xcss.xcss.CSSStyleDelacration#getCssStyleKey <em>Css Style Key</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Css Style Key</em>' containment reference.
   * @see #getCssStyleKey()
   * @generated
   */
  void setCssStyleKey(CSSStyleKey value);

  /**
   * Returns the value of the '<em><b>Css Style Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Css Style Value</em>' containment reference.
   * @see #setCssStyleValue(CSSStyleValue)
   * @see mdd.coursework.xcss.xcss.XcssPackage#getCSSStyleDelacration_CssStyleValue()
   * @model containment="true"
   * @generated
   */
  CSSStyleValue getCssStyleValue();

  /**
   * Sets the value of the '{@link mdd.coursework.xcss.xcss.CSSStyleDelacration#getCssStyleValue <em>Css Style Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Css Style Value</em>' containment reference.
   * @see #getCssStyleValue()
   * @generated
   */
  void setCssStyleValue(CSSStyleValue value);

} // CSSStyleDelacration
