/**
 * generated by Xtext 2.24.0
 */
package mdd.coursework.xcss.xcss;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CSS Style Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdd.coursework.xcss.xcss.CSSStyleValue#getValue <em>Value</em>}</li>
 *   <li>{@link mdd.coursework.xcss.xcss.CSSStyleValue#getVariable <em>Variable</em>}</li>
 * </ul>
 *
 * @see mdd.coursework.xcss.xcss.XcssPackage#getCSSStyleValue()
 * @model
 * @generated
 */
public interface CSSStyleValue extends Expression
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(CSSStyleValueLiteral)
   * @see mdd.coursework.xcss.xcss.XcssPackage#getCSSStyleValue_Value()
   * @model containment="true"
   * @generated
   */
  CSSStyleValueLiteral getValue();

  /**
   * Sets the value of the '{@link mdd.coursework.xcss.xcss.CSSStyleValue#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(CSSStyleValueLiteral value);

  /**
   * Returns the value of the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' reference.
   * @see #setVariable(VariableDeclaration)
   * @see mdd.coursework.xcss.xcss.XcssPackage#getCSSStyleValue_Variable()
   * @model
   * @generated
   */
  VariableDeclaration getVariable();

  /**
   * Sets the value of the '{@link mdd.coursework.xcss.xcss.CSSStyleValue#getVariable <em>Variable</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(VariableDeclaration value);

} // CSSStyleValue
