/**
 * generated by Xtext 2.24.0
 */
package mdd.coursework.xcss.xcss;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mdd.coursework.xcss.xcss.XcssPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
