/**
 * generated by Xtext 2.24.0
 */
package mdd.coursework.xcss.xcss;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XCSS Style Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdd.coursework.xcss.xcss.XCSSStyleRule#getSelectors <em>Selectors</em>}</li>
 *   <li>{@link mdd.coursework.xcss.xcss.XCSSStyleRule#getVariableDeclarations <em>Variable Declarations</em>}</li>
 *   <li>{@link mdd.coursework.xcss.xcss.XCSSStyleRule#getCssStyleDeclarations <em>Css Style Declarations</em>}</li>
 * </ul>
 *
 * @see mdd.coursework.xcss.xcss.XcssPackage#getXCSSStyleRule()
 * @model
 * @generated
 */
public interface XCSSStyleRule extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Selectors</b></em>' containment reference list.
   * The list contents are of type {@link mdd.coursework.xcss.xcss.XCSSSelector}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selectors</em>' containment reference list.
   * @see mdd.coursework.xcss.xcss.XcssPackage#getXCSSStyleRule_Selectors()
   * @model containment="true"
   * @generated
   */
  EList<XCSSSelector> getSelectors();

  /**
   * Returns the value of the '<em><b>Variable Declarations</b></em>' containment reference list.
   * The list contents are of type {@link mdd.coursework.xcss.xcss.VariableDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable Declarations</em>' containment reference list.
   * @see mdd.coursework.xcss.xcss.XcssPackage#getXCSSStyleRule_VariableDeclarations()
   * @model containment="true"
   * @generated
   */
  EList<VariableDeclaration> getVariableDeclarations();

  /**
   * Returns the value of the '<em><b>Css Style Declarations</b></em>' containment reference list.
   * The list contents are of type {@link mdd.coursework.xcss.xcss.CSSStyleDelacration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Css Style Declarations</em>' containment reference list.
   * @see mdd.coursework.xcss.xcss.XcssPackage#getXCSSStyleRule_CssStyleDeclarations()
   * @model containment="true"
   * @generated
   */
  EList<CSSStyleDelacration> getCssStyleDeclarations();

} // XCSSStyleRule
