/**
 * generated by Xtext 2.24.0
 */
package mdd.coursework.xcss.xcss;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see mdd.coursework.xcss.xcss.XcssFactory
 * @model kind="package"
 * @generated
 */
public interface XcssPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "xcss";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.coursework.mdd/xcss/Xcss";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "xcss";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  XcssPackage eINSTANCE = mdd.coursework.xcss.xcss.impl.XcssPackageImpl.init();

  /**
   * The meta object id for the '{@link mdd.coursework.xcss.xcss.impl.XcssModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mdd.coursework.xcss.xcss.impl.XcssModelImpl
   * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getXcssModel()
   * @generated
   */
  int XCSS_MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XCSS_MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XCSS_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mdd.coursework.xcss.xcss.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mdd.coursework.xcss.xcss.impl.AbstractElementImpl
   * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getAbstractElement()
   * @generated
   */
  int ABSTRACT_ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Abstract Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link mdd.coursework.xcss.xcss.impl.XCSSStyleRuleImpl <em>XCSS Style Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mdd.coursework.xcss.xcss.impl.XCSSStyleRuleImpl
   * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getXCSSStyleRule()
   * @generated
   */
  int XCSS_STYLE_RULE = 2;

  /**
   * The feature id for the '<em><b>Selectors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XCSS_STYLE_RULE__SELECTORS = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Variable Declarations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XCSS_STYLE_RULE__VARIABLE_DECLARATIONS = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Css Style Declarations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XCSS_STYLE_RULE__CSS_STYLE_DECLARATIONS = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>XCSS Style Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XCSS_STYLE_RULE_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link mdd.coursework.xcss.xcss.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mdd.coursework.xcss.xcss.impl.VariableDeclarationImpl
   * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getVariableDeclaration()
   * @generated
   */
  int VARIABLE_DECLARATION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__VALUE = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Variable Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link mdd.coursework.xcss.xcss.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mdd.coursework.xcss.xcss.impl.ExpressionImpl
   * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 4;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link mdd.coursework.xcss.xcss.impl.XCSSSelectorImpl <em>XCSS Selector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mdd.coursework.xcss.xcss.impl.XCSSSelectorImpl
   * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getXCSSSelector()
   * @generated
   */
  int XCSS_SELECTOR = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XCSS_SELECTOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Pseudo Classes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XCSS_SELECTOR__PSEUDO_CLASSES = 1;

  /**
   * The number of structural features of the '<em>XCSS Selector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XCSS_SELECTOR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link mdd.coursework.xcss.xcss.impl.SelectorNameImpl <em>Selector Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mdd.coursework.xcss.xcss.impl.SelectorNameImpl
   * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getSelectorName()
   * @generated
   */
  int SELECTOR_NAME = 6;

  /**
   * The feature id for the '<em><b>Dot</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR_NAME__DOT = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR_NAME__NAME = 1;

  /**
   * The feature id for the '<em><b>Asterisk</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR_NAME__ASTERISK = 2;

  /**
   * The number of structural features of the '<em>Selector Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR_NAME_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link mdd.coursework.xcss.xcss.impl.PseudoClassImpl <em>Pseudo Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mdd.coursework.xcss.xcss.impl.PseudoClassImpl
   * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getPseudoClass()
   * @generated
   */
  int PSEUDO_CLASS = 7;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PSEUDO_CLASS__VALUE = 0;

  /**
   * The number of structural features of the '<em>Pseudo Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PSEUDO_CLASS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mdd.coursework.xcss.xcss.impl.CSSStyleDelacrationImpl <em>CSS Style Delacration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mdd.coursework.xcss.xcss.impl.CSSStyleDelacrationImpl
   * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getCSSStyleDelacration()
   * @generated
   */
  int CSS_STYLE_DELACRATION = 8;

  /**
   * The feature id for the '<em><b>Css Style Key</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSS_STYLE_DELACRATION__CSS_STYLE_KEY = 0;

  /**
   * The feature id for the '<em><b>Css Style Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSS_STYLE_DELACRATION__CSS_STYLE_VALUE = 1;

  /**
   * The number of structural features of the '<em>CSS Style Delacration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSS_STYLE_DELACRATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link mdd.coursework.xcss.xcss.impl.CSSStyleKeyImpl <em>CSS Style Key</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mdd.coursework.xcss.xcss.impl.CSSStyleKeyImpl
   * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getCSSStyleKey()
   * @generated
   */
  int CSS_STYLE_KEY = 9;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSS_STYLE_KEY__VALUE = 0;

  /**
   * The number of structural features of the '<em>CSS Style Key</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSS_STYLE_KEY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mdd.coursework.xcss.xcss.impl.CSSStyleValueImpl <em>CSS Style Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mdd.coursework.xcss.xcss.impl.CSSStyleValueImpl
   * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getCSSStyleValue()
   * @generated
   */
  int CSS_STYLE_VALUE = 10;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSS_STYLE_VALUE__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSS_STYLE_VALUE__VARIABLE = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>CSS Style Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSS_STYLE_VALUE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link mdd.coursework.xcss.xcss.impl.CSSStyleValueLiteralImpl <em>CSS Style Value Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mdd.coursework.xcss.xcss.impl.CSSStyleValueLiteralImpl
   * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getCSSStyleValueLiteral()
   * @generated
   */
  int CSS_STYLE_VALUE_LITERAL = 11;

  /**
   * The feature id for the '<em><b>Number</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSS_STYLE_VALUE_LITERAL__NUMBER = 0;

  /**
   * The feature id for the '<em><b>Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSS_STYLE_VALUE_LITERAL__SIZE = 1;

  /**
   * The feature id for the '<em><b>Word</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSS_STYLE_VALUE_LITERAL__WORD = 2;

  /**
   * The feature id for the '<em><b>Hex</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSS_STYLE_VALUE_LITERAL__HEX = 3;

  /**
   * The feature id for the '<em><b>Function</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSS_STYLE_VALUE_LITERAL__FUNCTION = 4;

  /**
   * The feature id for the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSS_STYLE_VALUE_LITERAL__STRING = 5;

  /**
   * The number of structural features of the '<em>CSS Style Value Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSS_STYLE_VALUE_LITERAL_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link mdd.coursework.xcss.xcss.impl.SizeLiteralImpl <em>Size Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mdd.coursework.xcss.xcss.impl.SizeLiteralImpl
   * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getSizeLiteral()
   * @generated
   */
  int SIZE_LITERAL = 12;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIZE_LITERAL__VALUE = 0;

  /**
   * The feature id for the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIZE_LITERAL__UNIT = 1;

  /**
   * The number of structural features of the '<em>Size Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIZE_LITERAL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link mdd.coursework.xcss.xcss.impl.NumberLiteralImpl <em>Number Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mdd.coursework.xcss.xcss.impl.NumberLiteralImpl
   * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getNumberLiteral()
   * @generated
   */
  int NUMBER_LITERAL = 13;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_LITERAL__VALUE = 0;

  /**
   * The number of structural features of the '<em>Number Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_LITERAL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mdd.coursework.xcss.xcss.impl.AdditionImpl <em>Addition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mdd.coursework.xcss.xcss.impl.AdditionImpl
   * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getAddition()
   * @generated
   */
  int ADDITION = 14;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__OPERATOR = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Addition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link mdd.coursework.xcss.xcss.impl.MultiplicationImpl <em>Multiplication</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mdd.coursework.xcss.xcss.impl.MultiplicationImpl
   * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getMultiplication()
   * @generated
   */
  int MULTIPLICATION = 15;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__OPERATOR = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Multiplication</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;


  /**
   * Returns the meta object for class '{@link mdd.coursework.xcss.xcss.XcssModel <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see mdd.coursework.xcss.xcss.XcssModel
   * @generated
   */
  EClass getXcssModel();

  /**
   * Returns the meta object for the containment reference list '{@link mdd.coursework.xcss.xcss.XcssModel#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see mdd.coursework.xcss.xcss.XcssModel#getElements()
   * @see #getXcssModel()
   * @generated
   */
  EReference getXcssModel_Elements();

  /**
   * Returns the meta object for class '{@link mdd.coursework.xcss.xcss.AbstractElement <em>Abstract Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Element</em>'.
   * @see mdd.coursework.xcss.xcss.AbstractElement
   * @generated
   */
  EClass getAbstractElement();

  /**
   * Returns the meta object for class '{@link mdd.coursework.xcss.xcss.XCSSStyleRule <em>XCSS Style Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XCSS Style Rule</em>'.
   * @see mdd.coursework.xcss.xcss.XCSSStyleRule
   * @generated
   */
  EClass getXCSSStyleRule();

  /**
   * Returns the meta object for the containment reference list '{@link mdd.coursework.xcss.xcss.XCSSStyleRule#getSelectors <em>Selectors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Selectors</em>'.
   * @see mdd.coursework.xcss.xcss.XCSSStyleRule#getSelectors()
   * @see #getXCSSStyleRule()
   * @generated
   */
  EReference getXCSSStyleRule_Selectors();

  /**
   * Returns the meta object for the containment reference list '{@link mdd.coursework.xcss.xcss.XCSSStyleRule#getVariableDeclarations <em>Variable Declarations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variable Declarations</em>'.
   * @see mdd.coursework.xcss.xcss.XCSSStyleRule#getVariableDeclarations()
   * @see #getXCSSStyleRule()
   * @generated
   */
  EReference getXCSSStyleRule_VariableDeclarations();

  /**
   * Returns the meta object for the containment reference list '{@link mdd.coursework.xcss.xcss.XCSSStyleRule#getCssStyleDeclarations <em>Css Style Declarations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Css Style Declarations</em>'.
   * @see mdd.coursework.xcss.xcss.XCSSStyleRule#getCssStyleDeclarations()
   * @see #getXCSSStyleRule()
   * @generated
   */
  EReference getXCSSStyleRule_CssStyleDeclarations();

  /**
   * Returns the meta object for class '{@link mdd.coursework.xcss.xcss.VariableDeclaration <em>Variable Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Declaration</em>'.
   * @see mdd.coursework.xcss.xcss.VariableDeclaration
   * @generated
   */
  EClass getVariableDeclaration();

  /**
   * Returns the meta object for the attribute '{@link mdd.coursework.xcss.xcss.VariableDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see mdd.coursework.xcss.xcss.VariableDeclaration#getName()
   * @see #getVariableDeclaration()
   * @generated
   */
  EAttribute getVariableDeclaration_Name();

  /**
   * Returns the meta object for the containment reference '{@link mdd.coursework.xcss.xcss.VariableDeclaration#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see mdd.coursework.xcss.xcss.VariableDeclaration#getValue()
   * @see #getVariableDeclaration()
   * @generated
   */
  EReference getVariableDeclaration_Value();

  /**
   * Returns the meta object for class '{@link mdd.coursework.xcss.xcss.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see mdd.coursework.xcss.xcss.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link mdd.coursework.xcss.xcss.XCSSSelector <em>XCSS Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XCSS Selector</em>'.
   * @see mdd.coursework.xcss.xcss.XCSSSelector
   * @generated
   */
  EClass getXCSSSelector();

  /**
   * Returns the meta object for the containment reference '{@link mdd.coursework.xcss.xcss.XCSSSelector#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Name</em>'.
   * @see mdd.coursework.xcss.xcss.XCSSSelector#getName()
   * @see #getXCSSSelector()
   * @generated
   */
  EReference getXCSSSelector_Name();

  /**
   * Returns the meta object for the containment reference list '{@link mdd.coursework.xcss.xcss.XCSSSelector#getPseudoClasses <em>Pseudo Classes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pseudo Classes</em>'.
   * @see mdd.coursework.xcss.xcss.XCSSSelector#getPseudoClasses()
   * @see #getXCSSSelector()
   * @generated
   */
  EReference getXCSSSelector_PseudoClasses();

  /**
   * Returns the meta object for class '{@link mdd.coursework.xcss.xcss.SelectorName <em>Selector Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Selector Name</em>'.
   * @see mdd.coursework.xcss.xcss.SelectorName
   * @generated
   */
  EClass getSelectorName();

  /**
   * Returns the meta object for the attribute '{@link mdd.coursework.xcss.xcss.SelectorName#isDot <em>Dot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dot</em>'.
   * @see mdd.coursework.xcss.xcss.SelectorName#isDot()
   * @see #getSelectorName()
   * @generated
   */
  EAttribute getSelectorName_Dot();

  /**
   * Returns the meta object for the attribute '{@link mdd.coursework.xcss.xcss.SelectorName#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see mdd.coursework.xcss.xcss.SelectorName#getName()
   * @see #getSelectorName()
   * @generated
   */
  EAttribute getSelectorName_Name();

  /**
   * Returns the meta object for the attribute '{@link mdd.coursework.xcss.xcss.SelectorName#getAsterisk <em>Asterisk</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Asterisk</em>'.
   * @see mdd.coursework.xcss.xcss.SelectorName#getAsterisk()
   * @see #getSelectorName()
   * @generated
   */
  EAttribute getSelectorName_Asterisk();

  /**
   * Returns the meta object for class '{@link mdd.coursework.xcss.xcss.PseudoClass <em>Pseudo Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pseudo Class</em>'.
   * @see mdd.coursework.xcss.xcss.PseudoClass
   * @generated
   */
  EClass getPseudoClass();

  /**
   * Returns the meta object for the attribute '{@link mdd.coursework.xcss.xcss.PseudoClass#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see mdd.coursework.xcss.xcss.PseudoClass#getValue()
   * @see #getPseudoClass()
   * @generated
   */
  EAttribute getPseudoClass_Value();

  /**
   * Returns the meta object for class '{@link mdd.coursework.xcss.xcss.CSSStyleDelacration <em>CSS Style Delacration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CSS Style Delacration</em>'.
   * @see mdd.coursework.xcss.xcss.CSSStyleDelacration
   * @generated
   */
  EClass getCSSStyleDelacration();

  /**
   * Returns the meta object for the containment reference '{@link mdd.coursework.xcss.xcss.CSSStyleDelacration#getCssStyleKey <em>Css Style Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Css Style Key</em>'.
   * @see mdd.coursework.xcss.xcss.CSSStyleDelacration#getCssStyleKey()
   * @see #getCSSStyleDelacration()
   * @generated
   */
  EReference getCSSStyleDelacration_CssStyleKey();

  /**
   * Returns the meta object for the containment reference '{@link mdd.coursework.xcss.xcss.CSSStyleDelacration#getCssStyleValue <em>Css Style Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Css Style Value</em>'.
   * @see mdd.coursework.xcss.xcss.CSSStyleDelacration#getCssStyleValue()
   * @see #getCSSStyleDelacration()
   * @generated
   */
  EReference getCSSStyleDelacration_CssStyleValue();

  /**
   * Returns the meta object for class '{@link mdd.coursework.xcss.xcss.CSSStyleKey <em>CSS Style Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CSS Style Key</em>'.
   * @see mdd.coursework.xcss.xcss.CSSStyleKey
   * @generated
   */
  EClass getCSSStyleKey();

  /**
   * Returns the meta object for the attribute '{@link mdd.coursework.xcss.xcss.CSSStyleKey#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see mdd.coursework.xcss.xcss.CSSStyleKey#getValue()
   * @see #getCSSStyleKey()
   * @generated
   */
  EAttribute getCSSStyleKey_Value();

  /**
   * Returns the meta object for class '{@link mdd.coursework.xcss.xcss.CSSStyleValue <em>CSS Style Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CSS Style Value</em>'.
   * @see mdd.coursework.xcss.xcss.CSSStyleValue
   * @generated
   */
  EClass getCSSStyleValue();

  /**
   * Returns the meta object for the containment reference '{@link mdd.coursework.xcss.xcss.CSSStyleValue#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see mdd.coursework.xcss.xcss.CSSStyleValue#getValue()
   * @see #getCSSStyleValue()
   * @generated
   */
  EReference getCSSStyleValue_Value();

  /**
   * Returns the meta object for the reference '{@link mdd.coursework.xcss.xcss.CSSStyleValue#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Variable</em>'.
   * @see mdd.coursework.xcss.xcss.CSSStyleValue#getVariable()
   * @see #getCSSStyleValue()
   * @generated
   */
  EReference getCSSStyleValue_Variable();

  /**
   * Returns the meta object for class '{@link mdd.coursework.xcss.xcss.CSSStyleValueLiteral <em>CSS Style Value Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CSS Style Value Literal</em>'.
   * @see mdd.coursework.xcss.xcss.CSSStyleValueLiteral
   * @generated
   */
  EClass getCSSStyleValueLiteral();

  /**
   * Returns the meta object for the containment reference '{@link mdd.coursework.xcss.xcss.CSSStyleValueLiteral#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Number</em>'.
   * @see mdd.coursework.xcss.xcss.CSSStyleValueLiteral#getNumber()
   * @see #getCSSStyleValueLiteral()
   * @generated
   */
  EReference getCSSStyleValueLiteral_Number();

  /**
   * Returns the meta object for the containment reference '{@link mdd.coursework.xcss.xcss.CSSStyleValueLiteral#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Size</em>'.
   * @see mdd.coursework.xcss.xcss.CSSStyleValueLiteral#getSize()
   * @see #getCSSStyleValueLiteral()
   * @generated
   */
  EReference getCSSStyleValueLiteral_Size();

  /**
   * Returns the meta object for the attribute '{@link mdd.coursework.xcss.xcss.CSSStyleValueLiteral#getWord <em>Word</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Word</em>'.
   * @see mdd.coursework.xcss.xcss.CSSStyleValueLiteral#getWord()
   * @see #getCSSStyleValueLiteral()
   * @generated
   */
  EAttribute getCSSStyleValueLiteral_Word();

  /**
   * Returns the meta object for the attribute '{@link mdd.coursework.xcss.xcss.CSSStyleValueLiteral#getHex <em>Hex</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Hex</em>'.
   * @see mdd.coursework.xcss.xcss.CSSStyleValueLiteral#getHex()
   * @see #getCSSStyleValueLiteral()
   * @generated
   */
  EAttribute getCSSStyleValueLiteral_Hex();

  /**
   * Returns the meta object for the attribute '{@link mdd.coursework.xcss.xcss.CSSStyleValueLiteral#getFunction <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Function</em>'.
   * @see mdd.coursework.xcss.xcss.CSSStyleValueLiteral#getFunction()
   * @see #getCSSStyleValueLiteral()
   * @generated
   */
  EAttribute getCSSStyleValueLiteral_Function();

  /**
   * Returns the meta object for the attribute '{@link mdd.coursework.xcss.xcss.CSSStyleValueLiteral#getString <em>String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>String</em>'.
   * @see mdd.coursework.xcss.xcss.CSSStyleValueLiteral#getString()
   * @see #getCSSStyleValueLiteral()
   * @generated
   */
  EAttribute getCSSStyleValueLiteral_String();

  /**
   * Returns the meta object for class '{@link mdd.coursework.xcss.xcss.SizeLiteral <em>Size Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Size Literal</em>'.
   * @see mdd.coursework.xcss.xcss.SizeLiteral
   * @generated
   */
  EClass getSizeLiteral();

  /**
   * Returns the meta object for the attribute '{@link mdd.coursework.xcss.xcss.SizeLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see mdd.coursework.xcss.xcss.SizeLiteral#getValue()
   * @see #getSizeLiteral()
   * @generated
   */
  EAttribute getSizeLiteral_Value();

  /**
   * Returns the meta object for the attribute '{@link mdd.coursework.xcss.xcss.SizeLiteral#getUnit <em>Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Unit</em>'.
   * @see mdd.coursework.xcss.xcss.SizeLiteral#getUnit()
   * @see #getSizeLiteral()
   * @generated
   */
  EAttribute getSizeLiteral_Unit();

  /**
   * Returns the meta object for class '{@link mdd.coursework.xcss.xcss.NumberLiteral <em>Number Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number Literal</em>'.
   * @see mdd.coursework.xcss.xcss.NumberLiteral
   * @generated
   */
  EClass getNumberLiteral();

  /**
   * Returns the meta object for the attribute '{@link mdd.coursework.xcss.xcss.NumberLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see mdd.coursework.xcss.xcss.NumberLiteral#getValue()
   * @see #getNumberLiteral()
   * @generated
   */
  EAttribute getNumberLiteral_Value();

  /**
   * Returns the meta object for class '{@link mdd.coursework.xcss.xcss.Addition <em>Addition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Addition</em>'.
   * @see mdd.coursework.xcss.xcss.Addition
   * @generated
   */
  EClass getAddition();

  /**
   * Returns the meta object for the containment reference '{@link mdd.coursework.xcss.xcss.Addition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see mdd.coursework.xcss.xcss.Addition#getLeft()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Left();

  /**
   * Returns the meta object for the attribute list '{@link mdd.coursework.xcss.xcss.Addition#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Operator</em>'.
   * @see mdd.coursework.xcss.xcss.Addition#getOperator()
   * @see #getAddition()
   * @generated
   */
  EAttribute getAddition_Operator();

  /**
   * Returns the meta object for the containment reference list '{@link mdd.coursework.xcss.xcss.Addition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see mdd.coursework.xcss.xcss.Addition#getRight()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Right();

  /**
   * Returns the meta object for class '{@link mdd.coursework.xcss.xcss.Multiplication <em>Multiplication</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiplication</em>'.
   * @see mdd.coursework.xcss.xcss.Multiplication
   * @generated
   */
  EClass getMultiplication();

  /**
   * Returns the meta object for the containment reference '{@link mdd.coursework.xcss.xcss.Multiplication#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see mdd.coursework.xcss.xcss.Multiplication#getLeft()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Left();

  /**
   * Returns the meta object for the attribute list '{@link mdd.coursework.xcss.xcss.Multiplication#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Operator</em>'.
   * @see mdd.coursework.xcss.xcss.Multiplication#getOperator()
   * @see #getMultiplication()
   * @generated
   */
  EAttribute getMultiplication_Operator();

  /**
   * Returns the meta object for the containment reference list '{@link mdd.coursework.xcss.xcss.Multiplication#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see mdd.coursework.xcss.xcss.Multiplication#getRight()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Right();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  XcssFactory getXcssFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link mdd.coursework.xcss.xcss.impl.XcssModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mdd.coursework.xcss.xcss.impl.XcssModelImpl
     * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getXcssModel()
     * @generated
     */
    EClass XCSS_MODEL = eINSTANCE.getXcssModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XCSS_MODEL__ELEMENTS = eINSTANCE.getXcssModel_Elements();

    /**
     * The meta object literal for the '{@link mdd.coursework.xcss.xcss.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mdd.coursework.xcss.xcss.impl.AbstractElementImpl
     * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getAbstractElement()
     * @generated
     */
    EClass ABSTRACT_ELEMENT = eINSTANCE.getAbstractElement();

    /**
     * The meta object literal for the '{@link mdd.coursework.xcss.xcss.impl.XCSSStyleRuleImpl <em>XCSS Style Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mdd.coursework.xcss.xcss.impl.XCSSStyleRuleImpl
     * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getXCSSStyleRule()
     * @generated
     */
    EClass XCSS_STYLE_RULE = eINSTANCE.getXCSSStyleRule();

    /**
     * The meta object literal for the '<em><b>Selectors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XCSS_STYLE_RULE__SELECTORS = eINSTANCE.getXCSSStyleRule_Selectors();

    /**
     * The meta object literal for the '<em><b>Variable Declarations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XCSS_STYLE_RULE__VARIABLE_DECLARATIONS = eINSTANCE.getXCSSStyleRule_VariableDeclarations();

    /**
     * The meta object literal for the '<em><b>Css Style Declarations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XCSS_STYLE_RULE__CSS_STYLE_DECLARATIONS = eINSTANCE.getXCSSStyleRule_CssStyleDeclarations();

    /**
     * The meta object literal for the '{@link mdd.coursework.xcss.xcss.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mdd.coursework.xcss.xcss.impl.VariableDeclarationImpl
     * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getVariableDeclaration()
     * @generated
     */
    EClass VARIABLE_DECLARATION = eINSTANCE.getVariableDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECLARATION__NAME = eINSTANCE.getVariableDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE_DECLARATION__VALUE = eINSTANCE.getVariableDeclaration_Value();

    /**
     * The meta object literal for the '{@link mdd.coursework.xcss.xcss.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mdd.coursework.xcss.xcss.impl.ExpressionImpl
     * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link mdd.coursework.xcss.xcss.impl.XCSSSelectorImpl <em>XCSS Selector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mdd.coursework.xcss.xcss.impl.XCSSSelectorImpl
     * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getXCSSSelector()
     * @generated
     */
    EClass XCSS_SELECTOR = eINSTANCE.getXCSSSelector();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XCSS_SELECTOR__NAME = eINSTANCE.getXCSSSelector_Name();

    /**
     * The meta object literal for the '<em><b>Pseudo Classes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XCSS_SELECTOR__PSEUDO_CLASSES = eINSTANCE.getXCSSSelector_PseudoClasses();

    /**
     * The meta object literal for the '{@link mdd.coursework.xcss.xcss.impl.SelectorNameImpl <em>Selector Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mdd.coursework.xcss.xcss.impl.SelectorNameImpl
     * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getSelectorName()
     * @generated
     */
    EClass SELECTOR_NAME = eINSTANCE.getSelectorName();

    /**
     * The meta object literal for the '<em><b>Dot</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECTOR_NAME__DOT = eINSTANCE.getSelectorName_Dot();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECTOR_NAME__NAME = eINSTANCE.getSelectorName_Name();

    /**
     * The meta object literal for the '<em><b>Asterisk</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECTOR_NAME__ASTERISK = eINSTANCE.getSelectorName_Asterisk();

    /**
     * The meta object literal for the '{@link mdd.coursework.xcss.xcss.impl.PseudoClassImpl <em>Pseudo Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mdd.coursework.xcss.xcss.impl.PseudoClassImpl
     * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getPseudoClass()
     * @generated
     */
    EClass PSEUDO_CLASS = eINSTANCE.getPseudoClass();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PSEUDO_CLASS__VALUE = eINSTANCE.getPseudoClass_Value();

    /**
     * The meta object literal for the '{@link mdd.coursework.xcss.xcss.impl.CSSStyleDelacrationImpl <em>CSS Style Delacration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mdd.coursework.xcss.xcss.impl.CSSStyleDelacrationImpl
     * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getCSSStyleDelacration()
     * @generated
     */
    EClass CSS_STYLE_DELACRATION = eINSTANCE.getCSSStyleDelacration();

    /**
     * The meta object literal for the '<em><b>Css Style Key</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CSS_STYLE_DELACRATION__CSS_STYLE_KEY = eINSTANCE.getCSSStyleDelacration_CssStyleKey();

    /**
     * The meta object literal for the '<em><b>Css Style Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CSS_STYLE_DELACRATION__CSS_STYLE_VALUE = eINSTANCE.getCSSStyleDelacration_CssStyleValue();

    /**
     * The meta object literal for the '{@link mdd.coursework.xcss.xcss.impl.CSSStyleKeyImpl <em>CSS Style Key</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mdd.coursework.xcss.xcss.impl.CSSStyleKeyImpl
     * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getCSSStyleKey()
     * @generated
     */
    EClass CSS_STYLE_KEY = eINSTANCE.getCSSStyleKey();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CSS_STYLE_KEY__VALUE = eINSTANCE.getCSSStyleKey_Value();

    /**
     * The meta object literal for the '{@link mdd.coursework.xcss.xcss.impl.CSSStyleValueImpl <em>CSS Style Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mdd.coursework.xcss.xcss.impl.CSSStyleValueImpl
     * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getCSSStyleValue()
     * @generated
     */
    EClass CSS_STYLE_VALUE = eINSTANCE.getCSSStyleValue();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CSS_STYLE_VALUE__VALUE = eINSTANCE.getCSSStyleValue_Value();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CSS_STYLE_VALUE__VARIABLE = eINSTANCE.getCSSStyleValue_Variable();

    /**
     * The meta object literal for the '{@link mdd.coursework.xcss.xcss.impl.CSSStyleValueLiteralImpl <em>CSS Style Value Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mdd.coursework.xcss.xcss.impl.CSSStyleValueLiteralImpl
     * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getCSSStyleValueLiteral()
     * @generated
     */
    EClass CSS_STYLE_VALUE_LITERAL = eINSTANCE.getCSSStyleValueLiteral();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CSS_STYLE_VALUE_LITERAL__NUMBER = eINSTANCE.getCSSStyleValueLiteral_Number();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CSS_STYLE_VALUE_LITERAL__SIZE = eINSTANCE.getCSSStyleValueLiteral_Size();

    /**
     * The meta object literal for the '<em><b>Word</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CSS_STYLE_VALUE_LITERAL__WORD = eINSTANCE.getCSSStyleValueLiteral_Word();

    /**
     * The meta object literal for the '<em><b>Hex</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CSS_STYLE_VALUE_LITERAL__HEX = eINSTANCE.getCSSStyleValueLiteral_Hex();

    /**
     * The meta object literal for the '<em><b>Function</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CSS_STYLE_VALUE_LITERAL__FUNCTION = eINSTANCE.getCSSStyleValueLiteral_Function();

    /**
     * The meta object literal for the '<em><b>String</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CSS_STYLE_VALUE_LITERAL__STRING = eINSTANCE.getCSSStyleValueLiteral_String();

    /**
     * The meta object literal for the '{@link mdd.coursework.xcss.xcss.impl.SizeLiteralImpl <em>Size Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mdd.coursework.xcss.xcss.impl.SizeLiteralImpl
     * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getSizeLiteral()
     * @generated
     */
    EClass SIZE_LITERAL = eINSTANCE.getSizeLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIZE_LITERAL__VALUE = eINSTANCE.getSizeLiteral_Value();

    /**
     * The meta object literal for the '<em><b>Unit</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIZE_LITERAL__UNIT = eINSTANCE.getSizeLiteral_Unit();

    /**
     * The meta object literal for the '{@link mdd.coursework.xcss.xcss.impl.NumberLiteralImpl <em>Number Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mdd.coursework.xcss.xcss.impl.NumberLiteralImpl
     * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getNumberLiteral()
     * @generated
     */
    EClass NUMBER_LITERAL = eINSTANCE.getNumberLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBER_LITERAL__VALUE = eINSTANCE.getNumberLiteral_Value();

    /**
     * The meta object literal for the '{@link mdd.coursework.xcss.xcss.impl.AdditionImpl <em>Addition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mdd.coursework.xcss.xcss.impl.AdditionImpl
     * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getAddition()
     * @generated
     */
    EClass ADDITION = eINSTANCE.getAddition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__LEFT = eINSTANCE.getAddition_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADDITION__OPERATOR = eINSTANCE.getAddition_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__RIGHT = eINSTANCE.getAddition_Right();

    /**
     * The meta object literal for the '{@link mdd.coursework.xcss.xcss.impl.MultiplicationImpl <em>Multiplication</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mdd.coursework.xcss.xcss.impl.MultiplicationImpl
     * @see mdd.coursework.xcss.xcss.impl.XcssPackageImpl#getMultiplication()
     * @generated
     */
    EClass MULTIPLICATION = eINSTANCE.getMultiplication();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__LEFT = eINSTANCE.getMultiplication_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTIPLICATION__OPERATOR = eINSTANCE.getMultiplication_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__RIGHT = eINSTANCE.getMultiplication_Right();

  }

} //XcssPackage
