/*
 * generated by Xtext 2.24.0
 */
package mdd.coursework.xcss.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractXcssValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(mdd.coursework.xcss.xcss.XcssPackage.eINSTANCE);
		return result;
	}
}
