/*
 * generated by Xtext 2.24.0
 */
package mdd.coursework.xcss.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class XcssUiModule extends AbstractXcssUiModule {

	public XcssUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
