/**
 * generated by Xtext 2.24.0
 */
package mdd.coursework.xcss.tests;

import mdd.coursework.xcss.tests.XcssInjectorProvider;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(XcssInjectorProvider.class)
@SuppressWarnings("all")
public class XcssParsingTest {
}
