/*
 * generated by Xtext 2.24.0
 */
package mdd.coursework.xcss.ui;

import com.google.inject.Injector;
import mdd.coursework.xcss.ui.internal.XcssActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XcssExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(XcssActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		XcssActivator activator = XcssActivator.getInstance();
		return activator != null ? activator.getInjector(XcssActivator.MDD_COURSEWORK_XCSS_XCSS) : null;
	}

}
