/**
 * generated by Xtext 2.24.0
 */
package mdd.coursework.xcss.xcss.impl;

import mdd.coursework.xcss.xcss.CSSStyleDelacration;
import mdd.coursework.xcss.xcss.CSSStyleKey;
import mdd.coursework.xcss.xcss.CSSStyleValue;
import mdd.coursework.xcss.xcss.XcssPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>CSS Style Delacration</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link mdd.coursework.xcss.xcss.impl.CSSStyleDelacrationImpl#getCssStyleKey <em>Css Style Key</em>}</li>
 *   <li>{@link mdd.coursework.xcss.xcss.impl.CSSStyleDelacrationImpl#getCssStyleValue <em>Css Style Value</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CSSStyleDelacrationImpl extends MinimalEObjectImpl.Container implements CSSStyleDelacration
{
  /**
   * The cached value of the '{@link #getCssStyleKey() <em>Css Style Key</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCssStyleKey()
   * @generated
   * @ordered
   */
  protected CSSStyleKey cssStyleKey;

  /**
   * The cached value of the '{@link #getCssStyleValue() <em>Css Style Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCssStyleValue()
   * @generated
   * @ordered
   */
  protected CSSStyleValue cssStyleValue;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CSSStyleDelacrationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XcssPackage.Literals.CSS_STYLE_DELACRATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CSSStyleKey getCssStyleKey()
  {
    return cssStyleKey;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCssStyleKey(CSSStyleKey newCssStyleKey, NotificationChain msgs)
  {
    CSSStyleKey oldCssStyleKey = cssStyleKey;
    cssStyleKey = newCssStyleKey;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, XcssPackage.CSS_STYLE_DELACRATION__CSS_STYLE_KEY, oldCssStyleKey, newCssStyleKey);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCssStyleKey(CSSStyleKey newCssStyleKey)
  {
    if (newCssStyleKey != cssStyleKey)
    {
      NotificationChain msgs = null;
      if (cssStyleKey != null)
        msgs = ((InternalEObject)cssStyleKey).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - XcssPackage.CSS_STYLE_DELACRATION__CSS_STYLE_KEY, null, msgs);
      if (newCssStyleKey != null)
        msgs = ((InternalEObject)newCssStyleKey).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - XcssPackage.CSS_STYLE_DELACRATION__CSS_STYLE_KEY, null, msgs);
      msgs = basicSetCssStyleKey(newCssStyleKey, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XcssPackage.CSS_STYLE_DELACRATION__CSS_STYLE_KEY, newCssStyleKey, newCssStyleKey));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CSSStyleValue getCssStyleValue()
  {
    return cssStyleValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCssStyleValue(CSSStyleValue newCssStyleValue, NotificationChain msgs)
  {
    CSSStyleValue oldCssStyleValue = cssStyleValue;
    cssStyleValue = newCssStyleValue;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, XcssPackage.CSS_STYLE_DELACRATION__CSS_STYLE_VALUE, oldCssStyleValue, newCssStyleValue);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCssStyleValue(CSSStyleValue newCssStyleValue)
  {
    if (newCssStyleValue != cssStyleValue)
    {
      NotificationChain msgs = null;
      if (cssStyleValue != null)
        msgs = ((InternalEObject)cssStyleValue).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - XcssPackage.CSS_STYLE_DELACRATION__CSS_STYLE_VALUE, null, msgs);
      if (newCssStyleValue != null)
        msgs = ((InternalEObject)newCssStyleValue).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - XcssPackage.CSS_STYLE_DELACRATION__CSS_STYLE_VALUE, null, msgs);
      msgs = basicSetCssStyleValue(newCssStyleValue, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XcssPackage.CSS_STYLE_DELACRATION__CSS_STYLE_VALUE, newCssStyleValue, newCssStyleValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case XcssPackage.CSS_STYLE_DELACRATION__CSS_STYLE_KEY:
        return basicSetCssStyleKey(null, msgs);
      case XcssPackage.CSS_STYLE_DELACRATION__CSS_STYLE_VALUE:
        return basicSetCssStyleValue(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case XcssPackage.CSS_STYLE_DELACRATION__CSS_STYLE_KEY:
        return getCssStyleKey();
      case XcssPackage.CSS_STYLE_DELACRATION__CSS_STYLE_VALUE:
        return getCssStyleValue();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case XcssPackage.CSS_STYLE_DELACRATION__CSS_STYLE_KEY:
        setCssStyleKey((CSSStyleKey)newValue);
        return;
      case XcssPackage.CSS_STYLE_DELACRATION__CSS_STYLE_VALUE:
        setCssStyleValue((CSSStyleValue)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case XcssPackage.CSS_STYLE_DELACRATION__CSS_STYLE_KEY:
        setCssStyleKey((CSSStyleKey)null);
        return;
      case XcssPackage.CSS_STYLE_DELACRATION__CSS_STYLE_VALUE:
        setCssStyleValue((CSSStyleValue)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case XcssPackage.CSS_STYLE_DELACRATION__CSS_STYLE_KEY:
        return cssStyleKey != null;
      case XcssPackage.CSS_STYLE_DELACRATION__CSS_STYLE_VALUE:
        return cssStyleValue != null;
    }
    return super.eIsSet(featureID);
  }

} //CSSStyleDelacrationImpl
