/**
 * generated by Xtext 2.24.0
 */
package mdd.coursework.xcss.xcss.impl;

import java.util.Collection;

import mdd.coursework.xcss.xcss.PseudoClass;
import mdd.coursework.xcss.xcss.SelectorName;
import mdd.coursework.xcss.xcss.XCSSSelector;
import mdd.coursework.xcss.xcss.XcssPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>XCSS Selector</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link mdd.coursework.xcss.xcss.impl.XCSSSelectorImpl#getName <em>Name</em>}</li>
 *   <li>{@link mdd.coursework.xcss.xcss.impl.XCSSSelectorImpl#getPseudoClasses <em>Pseudo Classes</em>}</li>
 * </ul>
 *
 * @generated
 */
public class XCSSSelectorImpl extends MinimalEObjectImpl.Container implements XCSSSelector
{
  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected SelectorName name;

  /**
   * The cached value of the '{@link #getPseudoClasses() <em>Pseudo Classes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPseudoClasses()
   * @generated
   * @ordered
   */
  protected EList<PseudoClass> pseudoClasses;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected XCSSSelectorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XcssPackage.Literals.XCSS_SELECTOR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SelectorName getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetName(SelectorName newName, NotificationChain msgs)
  {
    SelectorName oldName = name;
    name = newName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, XcssPackage.XCSS_SELECTOR__NAME, oldName, newName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(SelectorName newName)
  {
    if (newName != name)
    {
      NotificationChain msgs = null;
      if (name != null)
        msgs = ((InternalEObject)name).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - XcssPackage.XCSS_SELECTOR__NAME, null, msgs);
      if (newName != null)
        msgs = ((InternalEObject)newName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - XcssPackage.XCSS_SELECTOR__NAME, null, msgs);
      msgs = basicSetName(newName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XcssPackage.XCSS_SELECTOR__NAME, newName, newName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<PseudoClass> getPseudoClasses()
  {
    if (pseudoClasses == null)
    {
      pseudoClasses = new EObjectContainmentEList<PseudoClass>(PseudoClass.class, this, XcssPackage.XCSS_SELECTOR__PSEUDO_CLASSES);
    }
    return pseudoClasses;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case XcssPackage.XCSS_SELECTOR__NAME:
        return basicSetName(null, msgs);
      case XcssPackage.XCSS_SELECTOR__PSEUDO_CLASSES:
        return ((InternalEList<?>)getPseudoClasses()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case XcssPackage.XCSS_SELECTOR__NAME:
        return getName();
      case XcssPackage.XCSS_SELECTOR__PSEUDO_CLASSES:
        return getPseudoClasses();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case XcssPackage.XCSS_SELECTOR__NAME:
        setName((SelectorName)newValue);
        return;
      case XcssPackage.XCSS_SELECTOR__PSEUDO_CLASSES:
        getPseudoClasses().clear();
        getPseudoClasses().addAll((Collection<? extends PseudoClass>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case XcssPackage.XCSS_SELECTOR__NAME:
        setName((SelectorName)null);
        return;
      case XcssPackage.XCSS_SELECTOR__PSEUDO_CLASSES:
        getPseudoClasses().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case XcssPackage.XCSS_SELECTOR__NAME:
        return name != null;
      case XcssPackage.XCSS_SELECTOR__PSEUDO_CLASSES:
        return pseudoClasses != null && !pseudoClasses.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //XCSSSelectorImpl
